/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "claves_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
destroy_rpc_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, destroy_rpc, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_rpc_1(set_value_peticion p, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, set_value_rpc,
		(xdrproc_t) xdr_set_value_peticion, (caddr_t) &p,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_rpc_1(int key, struct get_value_respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_value_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_get_value_respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_rpc_1(set_value_peticion p, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, modify_value_rpc,
		(xdrproc_t) xdr_set_value_peticion, (caddr_t) &p,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_rpc_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_rpc_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
