/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logger.h"

bool_t
xdr_log_entry (XDR *xdrs, log_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->datetime, ~0))
		 return FALSE;
	return TRUE;
}
