/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGGER_H_RPCGEN
#define _LOGGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct log_entry {
	char *username;
	char *operation;
	char *datetime;
};
typedef struct log_entry log_entry;

#define LOGGER_PROG 0x314159265358979323
#define LOGGER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define log_operation 1
extern  int * log_operation_1(log_entry *, CLIENT *);
extern  int * log_operation_1_svc(log_entry *, struct svc_req *);
extern int logger_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define log_operation 1
extern  int * log_operation_1();
extern  int * log_operation_1_svc();
extern int logger_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_entry (XDR *, log_entry*);

#else /* K&R C */
extern bool_t xdr_log_entry ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGGER_H_RPCGEN */
